### ISSUE TITLE
encounter an error when invoke LibSVM.getInstance()

### ISSUE THREAD

**Issue by hithzf** [yctung/AndroidLibSVM#7]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.hzf.recognition, PID: 18386
                  java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memcpy" referenced by "/data/app/com.example.recognition-1/lib/arm/libjnilibsvm.so"...
                      at java.lang.Runtime.loadLibrary(Runtime.java:372)
                      at java.lang.System.loadLibrary(System.java:1076)
                      at umich.cse.yctung.androidlibsvm.LibSVM.<clinit>(LibSVM.java:14)

**Comment by yctung** [comment]
Hi, can you let me know your build sdk verison (or gradle setting?) and phone model?

**Comment by hithzf** [comment]
Hi, my gradle setting is below:
compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.example.recognition"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

**Comment by yctung** [comment]
Can I know which phone you are using? will you get the same error when you are using a different phone or even simulator

**Comment by karimAbdel-Qader** [comment]
can you provide a link to your repo so i can help you?

**Comment by NKrautkremer** [comment]
Hey yctung, first of all, thank you very much for this.
I think, i am facing exactly the same error as hithzf, this is my SO-question: https://stackoverflow.com/questions/54013811/app-works-fine-on-emulators-but-crashes-on-device-with-java-lang-unsatisfiedli/54015393#54015393
The Lib runs fine on any emulator, but crashes with the above error on my physical device. Since i don't have any , i cannot say if it would work on an other Android device.
I am using a Lenovo tablet with Android-23 and armeabi-v7a
I'd be happy to share my whole project if it helps
Appreciate the help, I have been stuck for many days now 
and thanks again for providing this awesome library!

**Comment by NKrautkremer** [comment]
Well, i tried my app on my girlfriend's Huawai p20 lite with Android 8.0 and arm64-v8a and it worked like a charm.
